
jobs:

- job: 'Test'
  pool:
    vmImage: 'macOS-latest'
  strategy:
    matrix:
      python38:
        python.version: '3.8'
      python39:
        python.version: '3.9'
      python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
    maxParallel: '4'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: curl -sSL https://install.python-poetry.org | python
    displayName: Install Poetry

  - script: |
      $HOME/.local/bin/poetry install
    displayName: 'Install dependencies'

  - script: |
      $HOME/.local/bin/poetry run pylint --rcfile=pylintrc protool
      $HOME/.local/bin/poetry run pylint --rcfile=pylintrc tests
    displayName: 'Lint'

  - script: |
      $HOME/.local/bin/poetry run mypy --ignore-missing-imports protool/
      $HOME/.local/bin/poetry run mypy --ignore-missing-imports tests/
    displayName: 'Type Check'

  # Disable it for now until we fixed the test
  # - script: |
  #     $HOME/.local/bin/poetry run pytest tests --cov=keyper --cov-report html --cov-report xml --doctest-modules --junitxml=junit/test-results.xml
  #   displayName: 'pytest'

  # - script: |
  #     $HOME/.local/bin/poetry run inlinecss.py htmlcov
  #   displayName: 'Inline CSS'

  # - task: PublishTestResults@2
  #   inputs:
  #     testResultsFiles: '**/test-results.xml'
  #     testRunTitle: 'Python $(python.version)'
  #   condition: succeededOrFailed()

  # # Publish Code Coverage Results
  # - task: PublishCodeCoverageResults@1
  #   inputs:
  #     codeCoverageTool: 'cobertura'
  #     summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml
  #     reportDirectory: $(System.DefaultWorkingDirectory)/htmlcov
